POST http://localhost:3000/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidG9kQGdtYWlsLmNvbSIsImlhdCI6MTc3MjI0ODQ1NCwiZXhwIjoxNzcyMjUyMDU0LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdCJ9.HwHTb-IXdmX4TZEd91D4UvHu_zKnvWERVj1f6-IWMpQ

{
  "password":"123456",
  "newPassword":"123456"
}