POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidG9kQGdtYWlsLmNvbSIsImlhdCI6MTc3MjI0NjIzNiwiZXhwIjoxNzcyMjQ5ODM2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdCJ9.eRVrh7l8VwhQWEBEaHD7XXzXQEEKChgYuTJLfom-Wpw

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc3MjI0NjIzNiwiZXhwIjoxNzcyMzMyNjM2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdCJ9.RI1aXY3725s2TTH1RNnuiJ3wZT8jh5IXvCI6_bbPQeQ"
}